version: '3.8'

services:
  goodhamburger.api:
    build:
      context: .
      dockerfile: GoodHamburger.WebAPI/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
